/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package ru.nsu.fit.opogibelnaya.task3;

import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.List;

class PrinterTest {
    @Test
    void test() {
        List<List<String>> input = new ArrayList<>();
        for (int i = 0; i < 4; i++) {
            input.add(new ArrayList<>());
        }

        input.get(0).add("hello!");
        input.get(0).add("I'm Ben!");

        input.get(1).add("Hi!");
        input.get(1).add("Everybody's lying.");
        input.get(1).add("I'm Mark!");

        input.get(2).add("Good morning, everyone!");
        input.get(2).add("My name is Gloria!");
        input.get(2).add("Today I want to tell you about...");

        input.get(3).add("Good night...");
        input.get(3).add("I'm going to sleep...");

        Printer printer = new Printer(input);
        printer.print();
    }
}
