/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package ru.nsu.fit.opogibelnaya.task2;

import static java.lang.Thread.sleep;

public class Parent {
    private final Thread myChild;

    public Parent() {
        myChild = new Thread(() -> {
            for (int i = 0; i < 5; i++) {
                System.out.println("Child!");
                try {
                    sleep(300);
                } catch (InterruptedException e) {
                    break;
                }
            }
        });
    }

    public void haveChild() {
        myChild.start();
        try {
            myChild.join();
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
        for (int i = 0; i < 5; i++) {
            System.out.println("I'm a parent!");
            try {
                sleep(500);
            } catch (InterruptedException e) {
                throw new RuntimeException(e);
            }
        }
    }
}