/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package ru.nsu.fit.opogibelnaya.task5;

import org.junit.jupiter.api.Test;

class ParentTest {
    @Test
    void test() {
        Parent parent = new Parent();
        parent.haveChild();
    }
}
