/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.nsu.fit.opogibelnaya.task1;

import org.junit.jupiter.api.Test;

class ParentTest {
    @Test void someLibraryMethodReturnsTrue() {
        Parent parent = new Parent();
        parent.haveChild();
    }
}
